Default: &defaults
  host: "localhost"
  port: 3000
  calendar: "https://www.google.com/calendar/feeds/datateknologsektionen@gmail.com/public/full"

Development:
  <<: *defaults

Test:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  <<: *defaults
