Default: &defaults
  host: "127.0.0.1"
  port: 3000
  calendar: "https://www.google.com/calendar/feeds/datateknologsektionen@gmail.com/public/full"
  analytics: "UA-28926914-1"

Development:
  <<: *defaults

Test:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  <<: *defaults
